services:
  - type: web
    name: jeevanandham-notes-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0
